version: 0.2

phases:
  install:
    commands:
      - echo In install phase...
      - npm install -g serverless
  build:
    commands:
      - echo In build phase...
      - serverless deploy -verbose

artifacts:
  files:
    - cd testPython
    - ls
    - testPython/serverless.yml
  discard-paths: yes

