phases:
  install:
    commands:
      - echo In install phase...
      - npm install -g serverless
  post_build:
    commands:
      - echo In post_build phase...
      - serverless deploy -verbose

artifacts:
  files:
    - serverless.yml
  discard-paths: yes

