version: 0.2

phases:
  install:
    commands:
      - echo In install phase...
      - npm install -g serverless
  build:
    commands:
      - echo In post_build phase...
      - cd testPython
      - serverless deploy -verbose

artifacts:
  files:
    - testPython/serverless.yml
  discard-paths: yes

