version: 0.2

phases:
  install:
    commands:
      - echo In install phase...
      - npm install -g serverless
  build:
    commands:
      - echo In build phase...
      - cd testPython
      - chmod 755 deploy.sh
      - ./deploy.sh

artifacts:
  files:
    - testPython/serverless.yml
  discard-paths: yes

