version: 0.2

phases:
  install:
    commands:
      - echo In install phase...
      - apt-get install npm
      - npm install serverless -g
  post_build:
    commands:
      - echo In post_build phase...
      - serverless deploy -verbose

artifacts:
  files:
    - serverless.yml
  discard-paths: yes

