version: 0.2

artifacts:
  files:
  - testPython/serverless.yml
  discard-paths: yes

phases:
  install:
    commands:
      - echo In install phase...
      - npm install -g serverless
  build:
    commands:
      - echo In build phase...
      - cd testPython
      - serverless deploy -verbose

